name: Pre-commit

on:
  push:
  pull_request:
  pull_request_target:

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: True
      matrix:
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: Install AgentScope
      run: |
        pip install -q -e .[full]
    - name: Install pre-commit
      run: |
        pre-commit install
    - name: Pre-commit starts
      run: |
        pre-commit run --all-files > pre-commit.log 2>&1 || true
        cat pre-commit.log
        if grep -q Failed pre-commit.log; then
          echo -e "\e[41m  [**FAIL**] Please install pre-commit and format your code first. \e[0m"
          exit 1
        fi
        echo -e "\e[46m  ********************************Passed******************************** \e[0m"
    - name: Read report
      id: read_report
      run: |
        echo "PRE_COMMIT_REPORT<<EOF" >> $GITHUB_ENV
        cat pre-commit.log >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
    - name: Comment PR with pre-commit.log
      if: github.event_name == 'pull_request'
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ## Pre-commit Format Check Results

          Hello everyone! The pre-commit hook has finished running, and the results are available below. If the report indicates any issues, please review and make the necessary changes as instructed to comply with the project's coding standards. Our goal is to maintain high-quality and consistent code across the project.

          ### 🧐 Check Results:
          ```plaintext
          ${{ env.PRE_COMMIT_REPORT }}
          ```
          ### 🔴 Action Required:
          If there are errors in the report, you are required to address them by modifying your code in accordance with the pre-commit guidelines. Follow the detailed instructions attached to each error if available.
          After making the required modifications, please commit your changes and push them again. The pre-commit checks will rerun to verify that all issues have been resolved.

          ### 💡 Tips for Success:
          It's highly recommended to run pre-commit checks locally before pushing your changes to avoid any surprises.
          Familiarize yourself with the project's contribution guidelines, so you're aware of the coding standards we follow.
          Thank you for your contribution to maintain a clean and orderly codebase!